try {
    console.log('line1');
    console.log('line2');
    console.log('try block');
} catch (error) {
    console.log(error);
    console.log('catch block');
}

console.log('outside try catch');